
#!/bin/bash

#databases path
ALPHAFOLD_DB=/path/to/alphafold_db

#singularity sif
ALPHAFOLD_SIF=/path/to/tcrmodel2.sif

#output directory
OUTPUT_DIR=/path/to/output_directory

# run tcrmodel singularity
singularity run --nv -B $ALPHAFOLD_DB  $ALPHAFOLD_SIF \
    --job_id=test_clsI_6kzw \
    --output_dir=$OUTPUT_DIR \
    --tcra_seq=AQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTSLLLIQSSQREQTSGRLNASLDKSSGRSTLYIAASQPGDSATYLCAVTNQAGTALIFGKGTTLSVSS \
    --tcrb_seq=NAGVTQTPKFQVLKTGQSMTLQCSQDMNHEYMSWYRQDPGMGLRLIHYSVGAGITDQGEVPNGYNVSRSTTEDFPLRLLSAAPSQTSVYFCASSYSIRGSRGEQFFGPGTRLTVL \
    --pep_seq=RLPAKAPLL \
    --mhca_seq=SHSLKYFHTSVSRPGRGEPRFISVGYVDDTQFVRFDNDAASPRMVPRAPWMEQEGSEYWDRETRSARDTAQIFRVNLRTLRGYYNQSEAGSHTLQWMHGCELGPDGRFLRGYEQFAYDGKDYLTLNEDLRSWTAVDTAAQISEQKSNDASEAEHQRAYLEDTCVE \
    --ori_db=$ALPHAFOLD_DB \
    --tp_db=/opt/tcrmodel2/data/databases \
    --relax_structures=True